name: snack_analyzer
description: A new Flutter project.
publish_to: 'none' # agar tidak dipublish ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.5
  get_storage: ^2.0.3
  camera: ^0.10.5+7
  google_ml_kit: ^0.18.0
  google_sign_in: ^6.1.5
  image_picker: ^1.1.1
  path_provider: ^2.1.2
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.2.0
  webview_flutter: ^4.2.2
  # firebase_core: ^2.24.0
  # firebase_auth: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/apple.png
    - assets/facebook.png
    - assets/SnackLogo.png
    - assets/Avatar.jpg
    - assets/Splash.png
    - assets/Icon_tips.png
    - assets/Icon_History.png
    - assets/garam.jpeg
    - assets/grafik.png
    - assets/garam2.jpg

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
