// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz3bn-UiQ3sRiUnKHq80u2kVZUS6t0IA8',
    appId: '1:489320720023:web:25e0903c49239a3e586bd2',
    messagingSenderId: '489320720023',
    projectId: 'analyzer-d157b',
    authDomain: 'analyzer-d157b.firebaseapp.com',
    storageBucket: 'analyzer-d157b.firebasestorage.app',
    measurementId: 'G-XFGE774Q4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABVvPl-5NhSh3dR5JSoUB3sIWQYMvQ224',
    appId: '1:489320720023:android:a8d1991e497352bf586bd2',
    messagingSenderId: '489320720023',
    projectId: 'analyzer-d157b',
    storageBucket: 'analyzer-d157b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAryHQPaSTB2owMH-BiJk-PjGn6GuARIAQ',
    appId: '1:489320720023:ios:450363223b439de2586bd2',
    messagingSenderId: '489320720023',
    projectId: 'analyzer-d157b',
    storageBucket: 'analyzer-d157b.firebasestorage.app',
    iosClientId: '489320720023-flg8gfigl1levollvovdtbfnmqb89p19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAryHQPaSTB2owMH-BiJk-PjGn6GuARIAQ',
    appId: '1:489320720023:ios:450363223b439de2586bd2',
    messagingSenderId: '489320720023',
    projectId: 'analyzer-d157b',
    storageBucket: 'analyzer-d157b.firebasestorage.app',
    iosClientId: '489320720023-flg8gfigl1levollvovdtbfnmqb89p19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz3bn-UiQ3sRiUnKHq80u2kVZUS6t0IA8',
    appId: '1:489320720023:web:2458fe48c22314ef586bd2',
    messagingSenderId: '489320720023',
    projectId: 'analyzer-d157b',
    authDomain: 'analyzer-d157b.firebaseapp.com',
    storageBucket: 'analyzer-d157b.firebasestorage.app',
    measurementId: 'G-1TFFQ4NMRX',
  );
}
